# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details

sudo: false

language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - DB=MYSQL CORE_RELEASE=3.1

matrix:
  include:
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3

before_script:
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - cd ~/builds/ss

script:
  - vendor/bin/phpunit --coverage-clover coverage.clover shop_stock/tests
  - wget https://scrutinizer-ci.com/ocular.phar
  - git remote rm origin
  - git remote add origin git@github.com:silvershop/silvershop-stock.git

branches:
  only:
    - master
